fix

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -6,7 +6,6 @@ pipeline {
     }
 
     stages {
-
         stage('Checkout') {
             steps {
                 echo '🧹 Cleaning workspace before fresh checkout...'
@@ -93,28 +92,19 @@ pipeline {
             steps {
                 echo '🔐 Bootstrapping Kubernetes ServiceAccount...'
                 sh '''
-                      export KUBECONFIG=/var/jenkins_home/kubeconfig.yaml
+                echo "📋 Checking cluster access..."
+                kubectl config current-context || {
+                echo "❌ No current context in kubeconfig!" >&2
+                exit 1
+                }
 
-                    echo "📁 KUBECONFIG Path: $KUBECONFIG"
-                    echo "📋 Verifying current Kubernetes context..."
-                    kubectl config current-context || {
-                        echo "❌ Cannot get current Kubernetes context. Check kubeconfig." >&2
-                        exit 1
-                    }
+                kubectl get nodes || {
+                echo "❌ Cannot connect to the Kubernetes cluster!" >&2
+                exit 1
+                }
 
-                    echo "📡 Checking Kubernetes cluster connectivity..."
-                    kubectl get nodes || {
-                        echo "❌ Cannot connect to cluster. Is the cluster running? Authenticated?" >&2
-                        exit 1
-                    }
-
-                    echo "📄 Applying service account YAML..."
-                    kubectl apply -f k8s/jenkins-sa.yaml || {
-                        echo "❌ Failed to apply ServiceAccount YAML." >&2
-                        exit 1
-                    }
-
-                    echo "✅ Service Account applied successfully."`
+                echo "📄 Applying service account YAML..."
+                kubectl apply -f k8s/jenkins-sa.yaml¡
                 '''
             }
         }
